[
  "vscode"
  "jetbrains-toolbox"
  "steam"
  "steam-unwrapped"
  "vscode-extension-github-copilot"
  "vscode-extension-ms-vscode-remote-remote-containers"
  "obsidian"
  "ffmpeg-full"
  "discord"
  "spotify"
]
